### ISSUE TITLE
util.varIntBuffer is not correctly implemented

### ISSUE THREAD

**Issue by sammy007** [zone117x/node-stratum-pool#111]
https://github.com/zone117x/node-stratum-pool/blob/master/lib/util.js#L78

https://en.bitcoin.it/wiki/Protocol_documentation#Variable_length_integer

Correct:
```
< 0xFD
<= 0xFFFF
<= 0xFFFFFFFF
```

Implemented:

```
< 0xFD
< 0xFFFF
< 0xFFFFFFFF
```

Blocks with amount of transactions > 65535 will be rejected. This is hilarious amount but still worth fixing.

**Comment by zone117x** [comment]
Nice find. Could you do a pull request? I could make you a project collaborator if you want?
