### ISSUE TITLE
reject reason: Low difficulty share

### ISSUE THREAD

**Issue by rvrsh3ll** [zone117x/node-stratum-pool#135]
I see this previous thread but, not sure on the reason/solution https://github.com/zone117x/node-stratum-pool/issues/8

Getting a lot of these errors. Anything I can do to remediate?

**Comment by rvrsh3ll** [comment]
"varDiff": {
            "minDiff": 2,
            "maxDiff": 100000,
            "targetTime": 100,
            "retargetTime": 30,
            "variancePercent": 30,
            "maxJump": 100

**Comment by savskii** [comment]
same problem here on Zcoin

**Comment by rvrsh3ll** [comment]
Seems like it's a network think. Comes and goes.
