### ISSUE TITLE
digibyte coin - groestlmyriad coin block-rejected!

### ISSUE THREAD

**Issue by trustfarm-dev** [zone117x/node-stratum-pool#140]
digibyte coin - groestlmyriad coin block-rejected!

I've setup digibyte myriad groestl algorithm for POOL
also, changed to support myr-groestl hashing.

# changed things:
1. multi-hashing support myr-groestl for digibyte.
2. getinfo api -> getblockchaininfo() , getnetworkinfo() , ...
   for interfacing with digibyte latest daemon.
3. adds  algoProperties.js to support myr-groestl

# procedure to produce.
There's several days of mining. finally I found 3 blocks.
but, NOMP said 
"(Thread 4) We thought a block was found but it was rejected by the daemon, share data: {"job":"a8d","ip":"182.252.10.64","port":3270,"worker":"D8xq5XPZKAYMQ-----------------------,"height":6260408,"blockReward":79656798873,"difficulty":32,"shareDiff":"362533.21566225","blockDiff":314672.733261021,"blockDiffActual":314672.733261021,"blockHash":"0000000000002e46eb5923a74fe9150834595ead2c891364b2b0e673f02ba2f6"}
2018-03-17 04:47:41 [Pool]      [digibyte-groestl] (Thread 4) Share accepted at diff 32/362533.21566225 by D8xq5XPZKAYMQC314V5z-------------- [x.x.x.x]
"

I don't know , why this happen, and digibyte daemon logs says nothing.

# ambiguity points

I also need to change node-stratum on jobManager.js 

for groestlmyriad ?
above is original code of node-stratum
```
    var coinbaseHasher = (function(){
        switch(options.coin.algorithm){
            case 'keccak':
            case 'blake':
            case 'fugue':
            case 'groestl':
                if (options.coin.normalHashing === true)
                    return util.sha256d;
                else
                    return util.sha256;
            default:
                return util.sha256d;
        }
    })();
```

# setup what I tested.

coins/digibyte.groestl.conf
```
{
    "name": "digibyte-groestl",
    "symbol": "DGB",
    "algorithm": "groestlmyriad"
}
```
pool_configs/digibyte.conf
```
{
    "enabled": true,
    "coin": "digibyte.groestl.json",

    ....

    "daemons": [
        {
            "host": "127.0.0.1",
            "port": 14022,
            "user": "n-----",
            "password": "D5-------------------------P1LY2pOp"
        }
    ],

    "p2p": {
        "enabled": true,
        "host": "127.0.0.1",
        "port": 12024,
        "disableTransactions": false
    },
    

```
digibyte daemon configuration.

```
rpcport=14022
port=12024
daemon=1
listen=1
server=1
algo=groestl
rpcworkqueue=32

blocknotify=/home/nomp/nomp/nodeomp/scripts/blocknotify 127.0.0.1:17117 digibyte-groestl %s
```

**Comment by trustfarm-dev** [comment]
@foxer666 's comments on sha256d hashing on blockheader.

**Comment by liang55** [comment]
help me.
how setup digibyte myriad groestl algorithm for POOL?


.digibyte/digibyte.config
'''
rpcuser=digibyteuser
rpcpassword=digibytepassword
algo=groestl
rpcport=20102
port=21102
'''
coins/digibyte.groestl.conf
'''
{
    "name": "digibyte-groestl",
    "symbol": "DGB",
    "algorithm": "groestlmyriad"
}
'''
changed things:
1.adds algoProperties.js to support myr-groestl
2.change node-stratum on jobManager.js

but ,the miner does not work properly in the myr-gr algorithm. first of all, my 100GH computing power showed 200MH in the NOMP myr-gr algorithm, and then I did not find a new block for some day. does your myr-gr mine pool work properly, can you give your myr-gr pool address? thank you

**Comment by trustfarm-dev** [comment]
@liang55 refer private pool   :    http://mineralpool.co.kr:3001 (digibyte-groestl) 
refer :: https://github.com/trustfarm-dev/node-open-mining-portal
https://github.com/trustfarm-dev/node-open-mining-portal
github.com/trustfarm/node-stratum-pool.git
https://github.com/trustfarm-dev/node-multi-hashing

Any good PR I pleased to accpets.

**Comment by trustfarm-dev** [comment]
It is now version issue.
You can solve it by yourself.
Good luck

**Comment by liang55** [comment]
node v8.4.0

**Comment by liang55** [comment]
thanks,i have succeeded,
i have a fix :
 //multiplier: Math.pow(2, 8)
I found three blocks and got a reward, but there is no Blocks information in the mine.
And the mining award did not automatically enter the miner's account.
