### ISSUE TITLE
Do you plan to develop asicboost support?

### ISSUE THREAD

**Issue by cornac** [zone117x/node-stratum-pool#164]
Bitmain upload firmware for s9 with asicboost support. Do you plan to develop asicboost support?

**Comment by bcmonster** [comment]
I am trying to get it figured out now to use with nomp.   If anyone has found any forks that could help please let us know or if some one wants to start a fork I will help where i can if it is not something that we can implement here.  I think all sha256 machines going forward are going to want it.

**Comment by HashUnlimited** [comment]
AsicBoost is an urban legend in terms of being controllable. 

https://bitcointalk.org/index.php?topic=1420978.0
