### ISSUE TITLE
Add posibility to set pubkey instead of address

### ISSUE THREAD

**Issue by wargo32** [zone117x/node-stratum-pool#180]
Because it is required to use pubkey for POS coins, please add possibility to use pubkey as pool's address instead of normal addresses, so coins can be mined if wallet is outside server.

Currently, wallets needs to be on coin's daemon and NOMP uses `validateaddress` to get pubkey. There is `validatepubkey` to do validation (I am not sure all clients have it).

This can be applied for private mining or non-standard payment system.

**Comment by HashUnlimited** [comment]
An "address" is kind of typo-safe to a certain level, a pubkey isn't. You can always skip the validation and just submit your result to the daemon.
