### ISSUE TITLE
[Windows] Process finished with exit code -1073740940

### ISSUE THREAD

**Issue by sirsavary** [zone117x/node-stratum-pool#34]
Upon startup stratum-pool crashes with no useful error and brings down the rest of the application with it. This has only occurred on my Windows 8 machine and did not appear on my Debian 7 server but I am still trying to replicate on Debian. Before the crash, I get the following output:

debug: [system] Starting pool for LuckyCoin [LKY]
debug: [system] Connecting to daemon(s)
debug: [system] Daemon instance 0 is running on testnet
debug: [system] Connected to daemon via RPC

Sometimes the last line does not show, leading me to believe the error is occurring while the pool initialization is happening. Going to try changing some things with the coin daemon to see if I get different results.

**Comment by blowsie** [comment]
@sirsavary did you find the cause of the 1073740940 error? I am experiencing it in another plugin.

**Comment by sirsavary** [comment]
@blowsie Don't believe I ever found the cause of it. My solution was to push code to a Linux server and run it from there. As far as I can tell some of node-stratum-pool's dependencies won't build on Windows.

**Comment by blowsie** [comment]
@sirsavary In my scenario , I found this error to be occurring in node `11+` but not in node `0.10.37`
