### ISSUE TITLE
Abusing users are coming!

### ISSUE THREAD

**Issue by miningpoolhub** [zone117x/node-stratum-pool#41]
Hi
I am running a Darkcoin pool.
Yesterday there was some ridiculous hashrate increase and the pool didn't notice that this was abusing user.

Actually darkcoin's difficulty starts from 0.01 for normal 280x gpu.
It may go up 0.02 but I saw difficuclty upto 0.32 for some person. It's impossible!

Actually shares with difficulty 0.08 is very rare, since one miner rig can't handle 8 gpu I think.

When I block that person, he changed IP, ID, and constantly pushed hashes to my pool overnight.

Why is this abusing happen?
I saw other types of abusing on maxcoin pool which isn't running by node-stratum
and I was so tired of monitoring the pool. I launched darkcoin with node-stratum hoping that it may block abusing users well.

It doesn't work well I think.
I think each user's hash must be checked by their difficulty value and block them.
Is it possible?
Or find them by investigating some accumulated average statistics.

I can say more things about abusing people.
There are two types.
One is inputting same difficulty many many times, and the other is inputting shares with false difficulty value.
1) Inputting same difficulty as 128 and 10 times a second with one worker name. As looking at my experience, this can't be the normal situation even when many miner rigs are using same worker name. Their difficulty value must be lowered to minimum when they use same worker name for many rigs. I learned it from python based stratum-mining Maxcoin pool.

2) Inputting shares with false difficulty value is what I am experiencing with Darkcoin.
The code I saw on node-stratum is just checking the minimal difficulty of every share must pass, not based on the difficulty what miner inserted. Is it right? Python based stratum-mining project works same as this too.

Please advise me. This is really big problem that many pool operators are experiencing.
I saw some dogecoin pool told that they suffered with abusing shares and he fixed it.
Sadly, he didn't open the code, I don't know what to do, abusing users are hoping pools until they are blocked.
And other maxcoin pool operator told me that he is blocking abusing users by monitoring
the log. He said some tips for finding abusing users is that abusing users' share never exceed some diff. Their shares never log 'Yay!'. Well, it's about the python based stratum-mining project but you will find hint that what I'm saying. 'Yay!' log in stratum-mining project is just for test code that which checks the share difficulty is greater than some value.

Many pool operators modified stratum for strict check and they didn't share it I think. If Maxcoin's biggest pool 1gh didn't block abusing or modify the stratum, many abusing users would stick to that pool, isn't it? But many of them came to my pool.

One day when I was happy with my pool, abusing users just inputted about 25% shares of my pool and found any blocks for two days. I noticed abusing that day, and still now, couldn't get any perfect solutions.

I think this kind of things must be took seriously for stratum.
Please help, I want to contribute code when I find the solution.

**Comment by taylorshuang** [comment]
@miningpoolhub I am a pool operator, and have the same problem, do you solve this problem? That person had a about 20% of pool hash but didn't find any block for several hours. z-nomp  has sercurity problem, anybody can fix this bug?
