### ISSUE TITLE
Block share is not marked/returned anymore

### ISSUE THREAD

**Issue by ppanther1000** [zone117x/node-stratum-pool#61]
Hi zone,

this pool server is great work. It's really time to move away from the hard maintainable python solutions.
## 
1. One of your last version worked well. But now the registed event ...

pool.on('share', function(isValidShare, isValidBlock, data){

... does not deliver any blockshares. Blocks are correctly submitted to coindaemon, but blockshares do not show up anymore with this event. Problem is not limited to a specific coin. Any idea? Regular shares correctly propagate to this event.
1. You added variable shareDiff. Vardiff difficulty is limit to 512. But some shares occur with shareDiff 1000 or even 5000. Is data.shareDiff calculated correctly and should this diff be used to reward miner instead of data.difficulty?

Thank you very much,
PPanther

**Comment by liang55** [comment]
use master branch.
The mining award did not automatically enter the miner's account.
In addition, I found three blocks and received a reward, but there is no Blocks information displayed in the mine.
