### ISSUE TITLE
Lot of invalid low difficulty share rejects

### ISSUE THREAD

**Issue by bart-is** [zone117x/node-stratum-pool#8]
I launched this software on a live pool replacing the previous python's software but I was getting tons of low difficulty share rejects. I believe they were wrong because it didn't happen with the previous software. I had vardiff disabled to don't introduce unnecessary variables. Do you think you can help? I really like this software and I'd love to switch to it but it doesn't seem to work reliably. I can offer some BTC bounty if you can fix it + if you could add some features that I need (I messaged you on Skype but you didn't reply yet). Thanks!

**Comment by robsske** [comment]
Ive also issues with this. Who can help me out?!
